---
- name: "Avi SE | KVM | check total no of vfs and total intf names are equal or not"
  fail:
    msg: " Total no of vfs {{ total_num_vfs }} is not equal to the total no of virt_intf_name {{ virt_intf_name | length }}"
  when: total_num_vfs != virt_intf_name | length

- name: "Avi SE | KVM | Create directory on KVM Host"
  file:
   path: /root/{{ kvm_vm_hostname }}
   state: directory

- name: "Avi SE | KVM | Get the cloud uuid from Default-Cloud"
  avi_api_session:
    controller: "{{ vm_ctrl_ip }}"
    username: "{{ vm_ctrl_username }}"
    password: "{{ vm_ctrl_password }}"
    tenant: "admin"
    api_version: "{{ vm_ctrl_version }}"
    http_method: get
    path: "cloud?name=Default-Cloud"
  register: se_cloud_data

- name: "Avi SE | KVM | Get a token from the Avi Controller"
  avi_api_session:
    controller: "{{ vm_ctrl_ip }}"
    username: "{{ vm_ctrl_username }}"
    password: "{{ vm_ctrl_password }}"
    tenant: "admin"
    api_version: "{{ vm_ctrl_version }}"
    http_method: get
    path: securetoken-generate?cloud_uuid={{ se_cloud_data.obj.results[0].uuid }}
  register: se_authtoken
  when: se_auth_token is undefined

- name:  Avi SE | KVM | Image deploy | generate SE image on the controller
  avi_api_session:
    controller: "{{ vm_ctrl_ip }}"
    username: "{{ vm_ctrl_username }}"
    password: "{{ vm_ctrl_password }}"
    api_version: "{{ vm_ctrl_version }}"
    http_method: post
    path: 'fileservice/seova'
    timeout: 600
    data:
      file_format: qcow2
  when: kvm_vm_base_img is undefined

- name: "Avi SE | KVM | Get the se.qcow2 from the Avi Controller"
  avi_api_fileservice:
    controller: "{{ vm_ctrl_ip }}"
    username: "{{ vm_ctrl_username }}"
    password: "{{ vm_ctrl_password }}"
    upload: false
    path: seova
    file_path: /root/{{ kvm_vm_hostname }}/se.qcow2
    params:
      file_format: qcow2
    api_version: "{{ vm_ctrl_version }}"
  when: kvm_vm_base_img is undefined

- name: "Avi SE | KVM | SET the token"
  set_fact:
    se_auth_token: "{{ se_authtoken.obj.auth_token }}"
  when: se_auth_token is undefined

- debug: msg="Recieved Authentication {{ se_auth_token }} from {{ vm_ctrl_ip }}"
